services:
  app:
    build: .
    container_name: bookstore_app
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - bookstore_network

  db:
    image: mysql:8.0
    container_name: bookstore_db
    environment:
      MYSQL_DATABASE: bookstore_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - bookstore_network

networks:
  bookstore_network:
    driver: bridge